name: Linkcheck

on:
  workflow_dispatch:
    inputs:
      base_url:
        type: string
        default: https://watertap.readthedocs.io/en/latest/
        required: false
        description: Base url to check
      ignore_url_regex:
        description: URLs matching this regex will not be checked
        type: choice
        required: false
        default: ".*(?:en/(?!latest|stable)).*"
        options:
        - ".*(?:en/(?!latest|stable)).*"
        - ""
  schedule:
    # run daily at 12:00 pm UTC (8 am ET/5 am PT)
    - cron: '0 12 * * *'
  # FIXME remove once we're reasonably sure it works
  # (workflow_dispatch and schedule triggers only work from the default branch)
  push:

jobs:
  linkchecker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install linkchecker
      run: |
        pip install "linkchecker==10.1.*"
        # linkchecker refuses to load files from its own installation directory if they are world-writable
        linkchecker_pkg_dir=$(python -c 'import linkcheck as l, pathlib as p; print(p.Path(l.__file__).parent.resolve())')
        chmod -R o-w "$linkchecker_pkg_dir"
        linkchecker --version
    - name: Run linkchecker
      env:
        _url_to_check: ${{ inputs.base_url || 'https://watertap.readthedocs.io/en/latest/' }}
        _ignore_url_regex: ${{ inputs.ignore_url_regex || '.*(?:en/(?!latest|stable)).*' }}
      run: |
        linkchecker --ignore-url="$_ignore_url_regex" $_url_to_check

